### ISSUE TITLE
Fix XKCD 20241110

### ISSUE THREAD

**Issue by cesaralba** [cesaralba/cosecha#90]
2024-11-10 22:39:48,238 [38926:MainThread@root ERROR          39059ms]:/home/LIVE/CosechaPython/wrk/libs/Cosecha/Crawler.py@112 Crawler(crawl) 'XKCDhistory': problem:<class 'AttributeError'> 'NoneType' object has no attribute 'attrs'
2024-11-10 22:39:48,239 [38926:MainThread@root ERROR          39061ms]:/home/LIVE/CosechaPython/wrk/libs/Cosecha/Crawler.py@113 'NoneType' object has no attribute 'attrs'
Traceback (most recent call last):
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Crawler.py", line 92, in crawl
    self.obj.downloadPage()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Sites/XKCD.py", line 49, in downloadPage
    infoImg = findComicImg(pagBase.data, title=metas['title'], here=self.URL)
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Sites/XKCD.py", line 191, in findComicImg
    result['comment'] = imgLink.attrs['title']
                        ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attrs'
Stack (most recent call last):
  File "/home/LIVE/CosechaPython/wrk/bin/DescargaCosecha.py", line 77, in <module>
    main(config)
  File "/home/LIVE/CosechaPython/wrk/bin/DescargaCosecha.py", line 61, in main
    cosecha.go()
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Harvest.py", line 65, in go
    doSession(self)
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Harvest.py", line 48, in doSession
    self.download()
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Harvest.py", line 116, in download
    crawler.go()
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Crawler.py", line 64, in go
    self.crawl()
  File "/home/LIVE/CosechaPython/wrk/libs/Cosecha/Crawler.py", line 113, in crawl
    logging.exception(exc, stack_info=True)

**Comment by cesaralba** [comment]
ValueError: Unable to save image 'Comic 'xkcd' [1350] https://xkcd.com/1350/ -> Lorenz No data'. Dying

**Comment by cesaralba** [comment]
Nueva imagen que falla: 'https://xkcd.com/1525/'. 

El patrón es cosas con flash.
